### ISSUE TITLE
Missing 'Default value' columns in editor

### ISSUE THREAD

**Issue by sillkjc** [DLR-RM/RAFCON#849]
Hi all,
I'm attempting to do the 99 bottles tutorial. I ran into a problem where the 'Default value' column for scoped variables and ports seems to be missing. Maybe this is related to my desktop environment (KDE Plasmashell 5.12.9, Ubuntu 18.04)?

A horizontal scrollbar does appear but only for the 'Logical linkage' column.
I am also missing some other buttons, 'Add' or 'Set as start state'. Being not very familiar with RAFCON yet there may be other gui elements that are broken too. See screenshot below. 

RAFCON 0.14.6 installed via Pip.

Has anyone had a similar problem and found a way to make these elements display?

![Screenshot_20210527_135717](https://user-images.githubusercontent.com/73419795/119764188-4e4e8b00-bef4-11eb-8712-e8cc642a1458.png)

**Comment by sillkjc** [comment]
Nevermind, found under separate Data Linkage tab in state editor.

**Comment by sebastian-brunner** [comment]
The state editor of @sillkjc shows the "Logical Linkage" tab. You can select the "Data Linkage" tab just below. There you can manage your data (input, output and for container states also scoped variables).

**Comment by mfrigerio17** [comment]
Thanks I finally found it. Guys, the problem is that the interface shows the title "data linkage" AND "logical linkage" at the bottom of the state editor, even when the "logical linkage" tab is active... This is very confusing.

For the others with the same problem as me: you can switch mode(tab) with the small blue buttons in the top left of the state editor (e.g. the one that looks like a section of a chain)
